### PR TITLE
SSL enabled Linux Python builds

### PR DESCRIPTION
**Pull request by peardox**
Created the SSL enabled Python builds for Linux so PIP works properly with them

Tested 3.9.12 against two test projects (one of which installs every Data Science component) and against my own main project. Everything runs properly and PIP installs everything as expected using Embedded Python.

Built with Ubuntu 22.04 as it is the most likely system other devs will use for their own projects 

All Python versions are their current slightly out of date versions - need to experiment more to update the others.

### CODE REVIEW

**Comment by lmbelo** [comment]
We must place it in the CI. I will do it as possible.

**Comment by peardox** [comment]
Actually recent test imply more work is needed on this front.

Now I've got my Steam Deck I tried to install my project on it (it eventually worked after a lot of hacking around - it was actually a lot simpler just installing the Windows version...)

Basically it appears as if PIP needs a staic build as building on one system won't install on abother usually due to slight variances in the ssl, crypt and ffi libraries.

Sadly Delphi can't build for the Steam Deck as it's Arch-based (headers/libraries aren't where the Ubuntu / Fedora ones are)

**Comment by lmbelo** [comment]
> Actually recent test imply more work is needed on this front.
> 
> Now I've got my Steam Deck I tried to install my project on it (it eventually worked after a lot of hacking around - it was actually a lot simpler just installing the Windows version...)
> 
> Basically it appears as if PIP needs a staic build as building on one system won't install on abother usually due to slight variances in the ssl, crypt and ffi libraries.
> 
> Sadly Delphi can't build for the Steam Deck as it's Arch-based (headers/libraries aren't where the Ubuntu / Fedora ones are)

You can use the PIP add-on.

**Comment by peardox** [comment]
See https://github.com/Embarcadero/PythonEnviroments/issues/20

I guess I could try installs in the PIP event but that's another problem with its own pitfalls

**Pull request closed without merging**
